/**
 * auto generated by graphql-codegen
 * DO NOT EDIT THIS FILE BY HAND
 */

import { GraphQLResolveInfo } from 'graphql';
import { ContextType } from '../utils/createContext';
export type Maybe<T> = T | null;

/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string,
  String: string,
  Boolean: boolean,
  Int: number,
  Float: number,
};

export type Query = {
   __typename?: 'Query',
  recipes: Array<RecipeData>,
};

export type RecipeData = {
   __typename?: 'RecipeData',
  id: Scalars['ID'],
  title: Scalars['String'],
  subtitle?: Maybe<Scalars['String']>,
  tags?: Maybe<Scalars['String']>,
  ranking: Scalars['Int'],
  servings?: Maybe<Scalars['String']>,
  difficulty: Scalars['Int'],
  preparationTime?: Maybe<Scalars['String']>,
  cookingTime?: Maybe<Scalars['String']>,
  restTime?: Maybe<Scalars['String']>,
  preparations?: Maybe<Scalars['String']>,
  source?: Maybe<Scalars['String']>,
  categoryId: Scalars['ID'],
};



export type ResolverTypeWrapper<T> = Promise<T> | T;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult;


export type StitchingResolver<TResult, TParent, TContext, TArgs> = {
  fragment: string;
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};

export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> =
  | ResolverFn<TResult, TParent, TContext, TArgs>
  | StitchingResolver<TResult, TParent, TContext, TArgs>;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => AsyncIterator<TResult> | Promise<AsyncIterator<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<TResult, TKey extends string, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
  resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
  resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
  | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TKey extends string, TParent = {}, TContext = {}, TArgs = {}> =
  | ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
  | SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<TTypes, TParent = {}, TContext = {}> = (
  parent: TParent,
  context: TContext,
  info: GraphQLResolveInfo
) => Maybe<TTypes>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult = {}, TParent = {}, TContext = {}, TArgs = {}> = (
  next: NextResolverFn<TResult>,
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;

/** Mapping between all available schema types and the resolvers types */
export type ResolversTypes = {
  Query: ResolverTypeWrapper<{}>,
  RecipeData: ResolverTypeWrapper<RecipeData>,
  ID: ResolverTypeWrapper<Scalars['ID']>,
  String: ResolverTypeWrapper<Scalars['String']>,
  Int: ResolverTypeWrapper<Scalars['Int']>,
  Boolean: ResolverTypeWrapper<Scalars['Boolean']>,
};

/** Mapping between all available schema types and the resolvers parents */
export type ResolversParentTypes = {
  Query: {},
  RecipeData: RecipeData,
  ID: Scalars['ID'],
  String: Scalars['String'],
  Int: Scalars['Int'],
  Boolean: Scalars['Boolean'],
};

export type QueryResolvers<ContextType = ContextType, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  recipes?: Resolver<Array<ResolversTypes['RecipeData']>, ParentType, ContextType>,
};

export type RecipeDataResolvers<ContextType = ContextType, ParentType extends ResolversParentTypes['RecipeData'] = ResolversParentTypes['RecipeData']> = {
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>,
  title?: Resolver<ResolversTypes['String'], ParentType, ContextType>,
  subtitle?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  tags?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  ranking?: Resolver<ResolversTypes['Int'], ParentType, ContextType>,
  servings?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  difficulty?: Resolver<ResolversTypes['Int'], ParentType, ContextType>,
  preparationTime?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  cookingTime?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  restTime?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  preparations?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  source?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  categoryId?: Resolver<ResolversTypes['ID'], ParentType, ContextType>,
};

export type Resolvers<ContextType = ContextType> = {
  Query?: QueryResolvers<ContextType>,
  RecipeData?: RecipeDataResolvers<ContextType>,
};


/**
 * @deprecated
 * Use "Resolvers" root object instead. If you wish to get "IResolvers", add "typesPrefix: I" to your config.
*/
export type IResolvers<ContextType = ContextType> = Resolvers<ContextType>;
